//import "./axios.loader";
import "./component.loader";
import "./main.scss";
import "./Login/LoginForm";
import "./Registration/RegistrationForm";
import "./GiftRegistration/GiftRegistrationForm";
import "./GiftRequestList/GiftRequestList";
import "./MainNavigation/MainNavigation";
import "./InvitationPanel/InvitationPanel";